import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function GET() {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const margin = 50;
  let y = 800;

  const title = "Coaching Agreement | قرارداد کوچینگ";
  page.drawText(title, {
    x: margin,
    y,
    size: 18,
    font: fontBold,
    color: rgb(0.06, 0.09, 0.16),
  });

  y -= 30;
  page.drawText("Mindshift for Lifeshift • Sara Mahmodi • www.saramahmodi.com", {
    x: margin,
    y,
    size: 10,
    font,
    color: rgb(0.28, 0.34, 0.45),
  });

  y -= 35;

  const sections: Array<{ h: string; body: string[] }> = [
    {
      h: "1) Scope | دامنه خدمات",
      body: [
        "EN: Coaching is future-focused and action-oriented. It does not replace therapy, legal, or medical advice.",
        "FA: کوچینگ آینده‌محور و اقدام‌محور است و جایگزین درمان، مشاوره حقوقی یا پزشکی نیست.",
      ],
    },
    {
      h: "2) Confidentiality | محرمانگی",
      body: [
        "EN: All session content is confidential except where disclosure is required by law.",
        "FA: محتوای جلسات محرمانه است مگر در مواردی که قانون الزام کند.",
      ],
    },
    {
      h: "3) Client Responsibility | مسئولیت مراجع",
      body: [
        "EN: The client remains responsible for decisions, actions, and outcomes.",
        "FA: مسئولیت تصمیم‌ها، اقدام‌ها و نتایج با مراجع است.",
      ],
    },
    {
      h: "4) Scheduling & Rescheduling | زمان‌بندی و تغییر جلسه",
      body: [
        "EN: Rescheduling requires at least 24 hours notice.",
        "FA: تغییر زمان جلسه نیازمند اطلاع حداقل ۲۴ ساعت قبل است.",
      ],
    },
    {
      h: "5) Payments & Refunds | پرداخت و بازگشت وجه",
      body: [
        "EN: Packages are paid in advance. Unused sessions refundable within 30 days where applicable.",
        "FA: پکیج‌ها پیش‌پرداخت هستند. جلسات استفاده‌نشده (در صورت امکان) تا ۳۰ روز قابل بازگشت است.",
      ],
    },
    {
      h: "6) Contact | تماس",
      body: [
        "EN: WhatsApp: +358 41 753 9326 • Instagram: mindshift_for_lifeshift • LinkedIn: Sara Mahmodi",
        "FA: واتساپ: +358 41 753 9326 • اینستاگرام: mindshift_for_lifeshift • لینکدین: Sara Mahmodi",
      ],
    },
  ];

  const drawWrapped = (text: string, x: number, yPos: number, maxWidth: number, size: number) => {
    const words = text.split(" ");
    let line = "";
    const lines: string[] = [];
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      const width = font.widthOfTextAtSize(test, size);
      if (width > maxWidth) {
        lines.push(line);
        line = w;
      } else {
        line = test;
      }
    }
    if (line) lines.push(line);

    for (const l of lines) {
      page.drawText(l, { x, y: yPos, size, font, color: rgb(0.06, 0.09, 0.16) });
      yPos -= size + 4;
    }
    return yPos;
  };

  for (const s of sections) {
    page.drawText(s.h, {
      x: margin,
      y,
      size: 12,
      font: fontBold,
      color: rgb(0.06, 0.09, 0.16),
    });
    y -= 18;

    for (const line of s.body) {
      y = drawWrapped(line, margin, y, 595.28 - margin * 2, 10);
      y -= 6;
    }

    y -= 10;
    if (y < 120) {
      y = 800;
      pdfDoc.addPage([595.28, 841.89]);
    }
  }

  // Footer
  page.drawText("Generated by www.saramahmodi.com", {
    x: margin,
    y: 40,
    size: 9,
    font,
    color: rgb(0.28, 0.34, 0.45),
  });

  const pdfBytes = await pdfDoc.save();

  return new NextResponse(pdfBytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="coaching-agreement.pdf"',
      "Cache-Control": "public, max-age=3600",
    },
  });
}
